name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js Project
        run: npm run build

      - name: Deploy to Oracle Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          
          # Standard rsync flags: 
          # -r (recursive), -l (links), -p (perms), -t (times), -z (compress), -v (verbose)
          # --delete ensures files you deleted in Git are also deleted on the server
          ARGS: "-rlptzv --delete"
          
          # The source is the folder created by the Next.js build
          SOURCE: "out/"
          
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          
          TARGET: "/var/www/pathtonowordle"
          
          EXCLUDE: "/dist/, /node_modules/, /src/, .git/"
